# ==============================================================
# Audit of the numeric claims in the manuscript and SI against the
# pipeline's own outputs. Every number the text asserts about the
# measurement record is recomputed here from mobile_wswd.RData, so a
# re-run either reproduces the printed claim or shows what changed.
#
#   Rscript tests/audit_manuscript_claims.R
#
# CLAIM REFRESH (2026-09-25). The `claim` argument of every ok() call is what
# the DOCUMENTS say, so it has to move whenever they do. After the 300 m
# ATOPs-headquarters exclusion these were left on the pre-exclusion text and a
# clean run reported ten failures that were not failures - the documents were
# right and this file was stale. That is worse than no harness: it trains the
# reader to skim past FAIL. Refreshed below against the 25 Sep documents.
# The three correlation claims are the exception: those failures were real and
# are what caught SI S3 still quoting the submitted-era coefficients.
#
# Definitions follow 43_figure_s31_routes.R: the Goodrich route is
# excluded, and a "run" is one Site x calendar day.
#
# `date` is a fixed-MST wall clock carried with a UTC tzone attribute,
# so format(date, tz = "UTC") reads the MST clock directly. Do not
# convert it -- see REPRODUCIBILITY.md.
# ==============================================================
suppressPackageStartupMessages(library(data.table))

BASE <- Sys.getenv("SUNCOR_BASE", "~/Downloads/Suncor")
load(file.path(path.expand(BASE), "mobile_wswd.RData"))   # -> out
d <- as.data.table(out); rm(out)
stopifnot(attr(d$date, "tzone") == "UTC")
d <- d[Site != "Goodrich Corporation (Collins Aerospace)"]
d[, day := as.Date(date)]
d[, hr  := as.integer(format(date, "%H", tz = "UTC"))]
d[, ym  := as.integer(format(day, "%Y%m"))]

ok <- function(lab, got, want, tol = 0) {
  pass <- isTRUE(all.equal(got, want, tolerance = tol, check.attributes = FALSE))
  cat(sprintf("  [%s] %-46s got %-22s claim %s\n",
              if (pass) "OK  " else "FAIL", lab,
              paste(format(got), collapse = ","),
              paste(format(want), collapse = ",")))
  invisible(pass)
}

cat("\n== measurement record (Methods; Results 3.1) ==\n")
runs <- unique(d[, .(Site, day)])
ok("1-s measurements",        nrow(d),               2555285L)
ok("runs (Site x day)",       nrow(runs),            205L)
ok("unique sampling days",    uniqueN(runs$day),     203L)
ok("first day",               format(min(runs$day)), "2023-02-16")
ok("last day",                format(max(runs$day)), "2025-06-23")

cat("\n== weekday distribution (SI S3) ==\n")
wd <- table(factor(weekdays(unique(d[, .(day)])$day),
                   levels = c("Monday","Tuesday","Wednesday","Thursday","Friday")))
ok("Mon/Tue/Wed/Thu/Fri", as.integer(wd), c(8L, 39L, 48L, 50L, 58L))

cat("\n== hour of day (SI S3) ==\n")
ok("% between 9 am and 2 pm", round(100 * mean(d$hr >= 9 & d$hr < 14), 1), 88.6, 0.05)
frac <- d[, .(pct = round(100 * .N / nrow(d), 1)), by = hr][order(hr)]
ok("hours present (MST)", frac$hr, 7:16)
ok("hourly fractions", frac$pct,
   c(0.1, 2.8, 12.2, 19.3, 21.1, 20.6, 15.4, 6.2, 1.7, 0.6), 0.05)

cat("\n== pairwise correlations (SI S3) ==\n")
P <- c("Benzene_ppb","Toluene_ppb","Trimethylbenzene_ppb","Xylene_ppb",
       "Hydrogen_Sulfide_ppb","Hydrogen_Cyanide_ppb")
for (s in sort(unique(d$Site))) {
  cr <- cor(as.matrix(d[Site == s, ..P]), use = "pairwise.complete.obs")
  tag <- if (grepl("Suncor", s)) "Suncor" else "Holly "
  if (tag == "Suncor") {
    ok("Suncor toluene-xylene",      round(cr[2,4], 2), 0.94, 0.005)
    ok("Suncor TMB-xylene",          round(cr[3,4], 2), 0.90, 0.005)
    ok("Suncor benzene-TMB",         round(cr[1,3], 2), 0.70, 0.005)
  } else {
    ok("Holly toluene-xylene",       round(cr[2,4], 2), 0.84, 0.005)
    ok("Holly TMB-xylene",           round(cr[3,4], 2), 0.88, 0.005)
    ok("Holly toluene-TMB",          round(cr[2,3], 2), 0.75, 0.005)
  }
  cat(sprintf("       %s max |r| of H2S/HCN vs the aromatics: %.3f\n",
              tag, max(abs(cr[5:6, 1:4]))))
}

cat("\n== Table S3.1 and the claims that quote it ==\n")
cat("  Table S3.1 itself is generated by R_scripts/70_table_s31.R, which writes\n")
cat("  TABLE_S3.1.csv. If that file is present, check the text against it.\n")
tf <- file.path(BASE, "TABLE_S3.1.csv")
if (!file.exists(tf)) {
  cat("  [SKIP] TABLE_S3.1.csv not found - run R_scripts/70_table_s31.R first.\n")
} else {
  s <- fread(tf)
  setkey(s, pollutant)
  ok("benzene below MDL (Results 3.1)",  round(s["Benzene", pct_belowMDL]), 93)
  ok("H2S below MDL (Results 3.1)",      round(s["H2S",     pct_belowMDL]), 98)
  ok("HCN below MDL (Results 3.1)",      round(s["HCN",     pct_belowMDL]), 96)
  five <- s[pollutant != "HCN"]
  ok("analysis-set values, 5 pollutants (millions)",
     round(range(five$analysis) / 1e6, 2), c(1.44, 1.54), 0.005)
  # H2S now spans 199 days: the 2026-08-22 run retains it across the 2023 inlet
  # window, which affected the Eiger aromatics but not the Picarro. TMB is the
  # floor at 159. If H2S drops back to ~164 the retention has been undone.
  ok("sampling days, 5 pollutants",      range(five$n_days), c(159L, 199L))
  ok("H2S sampling days (2023 window retained)", s["H2S", n_days], 199L)
  # These four move when 03_checks_flags.R changes what HCN it keeps. They are
  # reported against what the documents currently state rather than asserted, so
  # a re-run tells you exactly which sentences to update instead of just failing.
  # 28-30 May 2025 is excluded as a calibration window, so HCN is 2 days and
  # 27,739 values below the previous run.
  DOC <- list(hcn_n = 478660L, hcn_days = 39L,
              hcn_from = "2025-01-22", hcn_to = "2025-06-23")
  cmp <- function(lab, got, doc) {
    same <- isTRUE(all.equal(got, doc, check.attributes = FALSE))
    cat(sprintf("  [%s] %-44s run %-14s documents say %s\n",
                if (same) "OK  " else "EDIT", lab,
                paste(format(got), collapse = ","), paste(format(doc), collapse = ",")))
  }
  cmp("HCN values",        s["HCN", analysis],                DOC$hcn_n)
  cmp("HCN sampling days", s["HCN", n_days],                  DOC$hcn_days)
  cmp("HCN window start",  as.character(s["HCN", first_day]), DOC$hcn_from)
  cmp("HCN window end",    as.character(s["HCN", last_day]),  DOC$hcn_to)
  ok("no value left without a published MDL", sum(s$n_no_mdl), 0L)
  cat("\n  maxima behind \"exceeded ...\" in Results 3.1 (ppb):\n")
  for (p in c("Benzene","Toluene","Xylene","Trimethylbenzene","H2S","HCN"))
    cat(sprintf("    %-18s max = %10.2f\n", p, s[p, max]))
}

cat("\n== CDPHE audit MDLs, as published in the quarterly packets ==\n")
mf <- file.path(BASE, "CDPHE_audit_MDLs.csv")
if (!file.exists(mf)) {
  cat("  [SKIP] CDPHE_audit_MDLs.csv not found - run R_scripts/69_cdphe_audit_mdls.R.\n")
} else {
  m <- fread(mf)
  ok("quarters covered", range(m$from_ym), c(202301L, 202504L))
  # the four values SI Table S1.2 got wrong, checked against the packets
  g <- function(cp, ym, col) m[compound == cp & from_ym == ym][[col]]
  ok("EMU HCN, 2025 Q1 (SI printed 0.18)", g("Hydrogen cyanide (HCN)", 202501L, "emu_mdl"), 18)
  ok("EMU HCN, 2023 Q4 (SI printed blank)", g("Hydrogen cyanide (HCN)", 202310L, "emu_mdl"), 5)
  ok("CAT benzene, 2025 Q2 (SI had no Q2)", g("Benzene", 202504L, "cat_mdl"), 0.3)
  ok("EMU TMB, 2024 Q4 (SI period ended Sep)", g("Trimethylbenzene", 202410L, "emu_mdl"), 0.44)
}

cat("\n== SI S4.1.2 driving speeds, from 43_figure_s31_routes.R ==\n")
sf <- file.path(BASE, "figureS31_segment_speed.csv")
if (!file.exists(sf)) {
  cat("  [SKIP] figureS31_segment_speed.csv not found - run",
      "GROUPS=J Rscript rerun_pipeline/MAKE_FIGURES.R\n")
} else {
  sp <- fread(sf); setkey(sp, quantity)
  g <- function(q) sp[q, value]
  ok("GPS segments (SI: 2,549,328)", g("n_segments"),          2549328)
  ok("median speed (SI: 26 km/h)",   round(g("p50")),          26)
  ok("IQR low (SI: 15 km/h)",        round(g("p25")),          15)
  ok("IQR high (SI: 39 km/h)",       round(g("p75")),          39)
  ok("95th percentile (SI: 74 km/h)", round(g("p95")),         74)
  ok("stationary (SI: 12%)",         round(g("pct_stationary_le1kmh")), 12)
  ok("1-s advance at p95 (SI: 21 m)", round(g("metres_per_second_at_p95")), 21)
  ok("500 m crossing at p95 (SI: 24 s)", round(g("seconds_to_cross_500m_at_p95")), 24)
  cat(sprintf("       for reference: only %.0f%% of segments fall in the submitted 30-60 km/h band\n",
              g("pct_in_30_60")))
}

cat("\n== Table S1.1 measurement periods, from the measurement files ==\n")
pf <- file.path(BASE, "TABLE_S1.1_periods.csv")
if (!file.exists(pf)) {
  cat("  [SKIP] TABLE_S1.1_periods.csv not found - run R_scripts/71_table_s11.R.\n")
} else {
  pr <- fread(pf)
  show <- function(dep, doc) {
    r <- pr[deployment == dep]
    if (!nrow(r)) { cat(sprintf("  [MISS] %-24s not in the csv\n", dep)); return(invisible()) }
    got <- sprintf("%s to %s", r$first_record[1], r$last_record[1])
    cat(sprintf("  [%s] %-24s data %-26s Table S1.1 says %s\n",
                if (identical(got, doc)) "OK  " else "EDIT", dep, got, doc))
  }
  # Updated 2026-08-22: these are the periods the REVISED SI actually carries,
  # verified against the installed document. All four were data-derived by
  # 71_table_s11.R and written into Table S1.1 in red, so EDIT here now means
  # the table has drifted from the measurement files - the check that is
  # actually useful from here on. The submitted wording is kept in comments.
  show("La Casa, summer 2023",    "2023-06-02 to 2023-08-08")   # submitted: to 2023-09-08
  show("La Casa, winter 2023/24", "2023-12-20 to 2024-02-20")   # submitted: unchanged
  show("La Casa, summer 2024",    "2024-06-24 to 2024-08-02")   # submitted: from 2024-06-26
  show("CDPHE vans, both",        "2023-02-16 to 2025-06-23")   # submitted: 2023-02-26 to 2025-03-13
  cat("\n  (\"Table S1.1 says\" is the wording in the REVISED SI. EDIT means the\n")
  cat("   table no longer matches the measurement files.)\n")
}
