# ==============================================================
# MAKE_FIGURES.R
# Regenerates ALL manuscript + SI figures from the fresh pipeline
# outputs. Run AFTER RUN_ALL_from_raw.R completes.
#
# Each figure GROUP runs in its own Rscript subprocess (package
# conflicts can't leak), with the preloads that scripts split from
# the sequential Rmd expect. CONTINUES on error and prints a
# pass/fail summary at the end — send failures back for fixing.
#
# Already regenerated by the pipeline itself (no need here):
#   Figure 3 (source-probability 6-panel)  <- R05
#   S6 plume + QA figures (FIG_H2S_*, QA_*) <- R07
#   Methane source-probability map          <- M04
#
# Usage:  Rscript MAKE_FIGURES.R
#         GROUPS="C,H" Rscript MAKE_FIGURES.R    # rerun specific groups
# ==============================================================

source("/Users/priyanka/Downloads/Suncor/rerun_pipeline/diagnostics_helpers.R")
diag_section("MAKE_FIGURES: regenerating manuscript + SI figures")

RS <- file.path(BASE, "R_scripts")

# group definition: name, description, preload lines, scripts (sourced in order)
GROUPS <- list(
  A = list(desc = "Timeplots / TimeVariation / correlation panels (S3)",
           pre = character(0),
           scripts = "07_timeplot_timevariation_ggally_correlation_plots.R"),
  B = list(desc = "Polar plot maps + combined figures (S3.9 etc.)",
           pre = character(0),
           scripts = c("08_polarplot_maps.R", "09_creating_figures.R")),
  C = list(desc = "FIGURE 2: 500 m segment maps + ratio maps (S4.5)",
           pre = c('load(file.path(BASE, "segment500_summaries_clean.RData"))',
                   'load(file.path(BASE, "segment500_summaries_acrossSites.RData"))'),
           scripts = c("15_maps_for_500_m_segment.R", "16_500_m_plotting_ratios.R")),
  D = list(desc = "Census block maps (S4.6)",
           pre = c('load(file.path(BASE, "censusblocks_suncor_terminal_BINWEIGHTED_AB.RData"))',
                   'load(file.path(BASE, "censusblocks_suncor_terminal_BINWEIGHTED_AB_overlap.RData"))'),
           scripts = "19_plot_maps_census_blocks.R"),
  E = list(desc = "Road network / road-type distributions (S4.4)",
           pre = character(0),
           scripts = "21_road_network_plot.R"),
  F = list(desc = "Distance-decay from facilities",
           pre = c('load(file.path(BASE, "bgcorrected_out_merge.RData"))',
                   'load(file.path(BASE, "all_colorado_roads.RData"))'),
           scripts = "22_distance_decay_function.R"),
  G = list(desc = "TRI proximity analysis",
           pre = character(0),
           scripts = "32_identifying_close_to_tri.R"),
  H = list(desc = "FIGURE 4 + hotspot figures (33 -> 34 -> 35 chained)",
           pre = character(0),
           scripts = c("33_final_hotspot_plots.R", "34_fancy_plots_of_hotspots.R",
                       "35_hotspot_figure_2.R")),
  I = list(desc = "HYSPLIT low-TMB/B trajectories (S4.8; slow, needs .gbl met files)",
           pre = character(0),
           scripts = "36_hysplit_of_lowest_trimethylbenzene_benzene_ratios.R"),
  J = list(desc = "FIGURE S1.1: daily-route GIF/panel",
           pre = character(0),
           scripts = "37_creating_gif_claude_figure_s1_1.R"),
  K = list(desc = "TRI proximity figures (S4.2 distributions + S4.3 buffers)",
           pre = character(0),
           scripts = c("41_tri_inside_outside_distributions.R",
                       "24_join_with_tri.R",
                       "25_tri_buffers_with_different_distances.R")),
  L = list(desc = "Sourceprob sensitivity diagnostics S5.1-S5.3 (SLOW: many maps)",
           pre = character(0),
           scripts = "27_hotspot_sensitivity_sensitivity.R"),
  M = list(desc = "Table S5.1 per-group reports (maps/scatter/polar + highday tables)",
           pre = character(0),
           scripts = "31_plotting.R")
)

sel <- Sys.getenv("GROUPS")
run_names <- if (nzchar(sel)) trimws(strsplit(sel, ",")[[1]]) else names(GROUPS)

results <- data.frame(group = character(0), desc = character(0),
                      status = character(0), minutes = numeric(0))

for (g in run_names) {
  if (!g %in% names(GROUPS)) { diag_msg("[SKIP] unknown group: ", g); next }
  gr <- GROUPS[[g]]
  diag_section(paste0("GROUP ", g, ": ", gr$desc))
  # build a temp runner script: libraries -> preloads -> figure scripts
  tmp <- file.path(PIPE, "logs", paste0("figgroup_", g, ".R"))
  lines <- c(
    sprintf('BASE <- "%s"', BASE),
    sprintf('source("%s")', file.path(RS, "01_libraries.R")),
    # 01_libraries loads plyr/raster AFTER dplyr, so select/mutate resolve to
    # the wrong packages in a fresh session (the interactive Rmd sessions had
    # dplyr re-attached on top). Re-attach dplyr LAST so its verbs win.
    'try(detach("package:dplyr"), silent = TRUE)',
    'suppressMessages(library(dplyr, warn.conflicts = FALSE))',
    gr$pre,
    # print.eval=TRUE is ESSENTIAL: knitr auto-prints bare plot objects (p1 etc.)
    # into open jpeg() devices; plain source() does not, silently writing EMPTY
    # figures. print.eval restores knitr-like behavior.
    sprintf('source("%s", echo = FALSE, print.eval = TRUE)', file.path(RS, gr$scripts))
  )
  writeLines(lines, tmp)
  t0 <- Sys.time()
  logf <- file.path(PIPE, "logs", paste0("FIG_", g, "_console.txt"))
  status <- system2("Rscript", tmp, stdout = logf, stderr = logf)
  mins <- round(as.numeric(difftime(Sys.time(), t0, units = "mins")), 1)
  ok <- identical(status, 0L)
  diag_msg(sprintf("  [%s] group %s in %.1f min  (log: %s)",
                   ifelse(ok, "PASS", "FAIL"), g, mins, basename(logf)))
  if (!ok) diag_msg("        last lines of log:\n        ",
                    paste(tail(readLines(logf, warn = FALSE), 5), collapse = "\n        "))
  results <- rbind(results, data.frame(group = g, desc = gr$desc,
                                       status = ifelse(ok, "PASS", "FAIL"), minutes = mins))
}

diag_section("MAKE_FIGURES summary")
for (i in seq_len(nrow(results)))
  diag_msg(sprintf("  [%s] %-2s %-55s %5.1f min",
                   results$status[i], results$group[i], results$desc[i], results$minutes[i]))
n_fail <- sum(results$status == "FAIL")
diag_msg("\n", nrow(results) - n_fail, " groups passed, ", n_fail, " failed.")
if (n_fail > 0) diag_msg("Send the FAIL logs (logs/FIG_<group>_console.txt) back for fixes;",
                         " rerun just those with GROUPS=\"X,Y\" Rscript MAKE_FIGURES.R")
write.csv(results, file.path(PIPE, "figure_generation_summary.csv"), row.names = FALSE)
