"""Give Table S3.1 a caption that states where every cell comes from and lists
the campaign date exclusions, which the code applies with no comment and the
submitted table referred to only as "additional contaminated data points".
"""
import sys
sys.path.insert(0, "/tmp")
from redfix import red_replace, count

UP = "/tmp/sifig/unpacked"
xml = open(f"{UP}/word/document.xml", encoding="utf-8").read()

OLD_CAP = ": Descriptive Statistics of the Mobile Measurements"
NEW_CAP = (
 ": Descriptive statistics of the mobile measurements. Every cell is "
 "generated by R_scripts/70_table_s31.R from the 58 monthly CDPHE CSVs and "
 "mobile_wswd.RData; no value is entered by hand, and the script writes "
 "TABLE_S3.1.csv alongside this table. The rows follow the filters the pipeline "
 "applies, in order. QA/QC voids a measurement only when a flag token is a null "
 "data qualifier in the CDPHE codebook; values below the MDL and negative values "
 "are retained. The campaign date exclusions are the hard-coded windows in "
 "03_checks_flags.R: 16 April - 20 September 2023 for all six pollutants, 13-14 "
 "August 2024 for the four aromatics, and, for HCN, 2-3 January 2025 together "
 "with everything on or before 22 January 2025 - which is why HCN is represented "
 "on 41 sampling days against about 165 for the other five. The analysis set is "
 "the record after the measured instrument-delay correction and native-cadence "
 "averaging. The below-MDL fraction uses the audit MDLs in Table S1.2, applied by "
 "lab and by period, with the last listed period carried forward past March 2025. "
 "All concentrations are given to two decimal places.")

assert count(xml, OLD_CAP) == 1
xml = red_replace(xml, OLD_CAP, NEW_CAP, label="Table S3.1 caption")

OLD_INTRO = (" provides a summary of the number and the percent of flagged "
             "measurements for each regulated pollutant.")
NEW_INTRO = (" reports, for each regulated pollutant, how many measurements "
             "survive each stage of the pipeline, how many sampling days and which "
             "date range they cover, the fraction below the audit method detection "
             "limit, and the distribution of the retained values.")
assert count(xml, OLD_INTRO) == 1
xml = red_replace(xml, OLD_INTRO, NEW_INTRO, label="Table S3.1 intro")

open(f"{UP}/word/document.xml", "w", encoding="utf-8").write(xml)
print("\ndocument.xml rewritten (%d bytes)" % len(xml.encode()))
