"""SI S6.5.1: the bias simulations were still reporting pre-correction values.

Both simulation summaries were regenerated by stage 2 of the 2026-08-21 run
(P09/P10, files dated 21 Aug 23:07). Current mean percent error:

  error_vs_true_stack_height_WWTP_0p5to5km_summary.csv
    dist        1m     10m     15m     20m     30m     50m
    0.5 km    +1.1    +0.4    -0.6    -1.9    -5.4   -15.4
    1.0 km    +0.2    +0.1    -0.1    -0.4    -1.2    -3.7
    1.5 km    +0.1     0.0    -0.0    -0.2    -0.5    -1.4
    2.0 km     0.0     0.0    -0.0    -0.1    -0.2    -0.7
    3-5 km     0.0     0.0    -0.0    -0.0    -0.1    -0.2 to -0.1

  error_vs_distance_crosswind_mismatch_WWTP_summary.csv
    dist       25m     50m    100m    200m    300m    500m
    0.5 km    -2.1    -8.1   -27.7   -69.1   -91.2   -99.8
    1.0 km    -0.6    -2.5    -9.3   -31.4   -55.1   -86.6
    2.0 km    -0.2    -0.8    -3.1   -11.8   -24.1   -51.4
    5.0 km    -0.1    -0.2    -0.8    -3.3    -7.3   -18.7

The SI quoted +111.9% at 1 m and -1541.6% at 50 m for 0.5 km -- two orders of
magnitude larger than the run now produces. That sensitivity collapsed when the
plume model was corrected: the vertical reflection series is now summed to
convergence rather than truncated, and once the vertical dispersion parameter
exceeds 1.6 times the boundary-layer depth the plume is treated as uniformly
mixed. Under those conditions the inferred rate stops depending strongly on
release height, even in the near field.

The crosswind simulation still shows strong near-field bias, so the section's
conclusion survives -- but it now rests on crosswind alignment alone, not on
source height. The narrative is rewritten accordingly.

Run from /tmp/sifig with unpacked/ present.
"""
import redfix
from redfix import red_replace as R

P = "unpacked/word/document.xml"
x = open(P, encoding="utf-8").read()

# ---- stack height, 0.5 km ------------------------------------------------
x = R(x, "When the true height was lower than assumed, emissions were overestimated by "
         "+111.9% for a 1 m source and +36.9% for a 10 m source.",
         "When the true height was lower than assumed, emissions were overestimated by only "
         "1.1% for a 1 m source and 0.4% for a 10 m source.",
         "S6.5.1 stack height 0.5 km, low")
x = R(x, "When the true height exceeded the assumed value, emissions were underestimated by "
         "-57.1% at 15 m, -186.2% at 20 m, -540.5% at 30 m, and -1541.6% at 50 m.",
         "When the true height exceeded the assumed value, emissions were underestimated by "
         "0.6% at 15 m, 1.9% at 20 m, 5.4% at 30 m and 15.4% at 50 m.",
         "S6.5.1 stack height 0.5 km, high")
x = R(x, "At the shortest distance considered (0.5 km), source-height mis-specification "
         "produced substantial bias (",
         "Even at the shortest distance considered (0.5 km), source-height mis-specification "
         "produced only modest bias (",
         "S6.5.1 near-field framing")
x = R(x, "These results indicate that near-field inversions are highly sensitive to "
         "effective source height (",
         "These results indicate that the inversion is insensitive to effective source height "
         "once the vertical reflection series is summed to convergence and the plume is "
         "treated as uniformly mixed above 1.6 boundary-layer depths (",
         "S6.5.1 stack height conclusion")

# ---- stack height, 1-5 km ------------------------------------------------
x = R(x, "At 1 km, mean error ranged from +20.1% for a 1 m source to -354.6% for a 50 m "
         "source, while by 1.5 km the corresponding range had narrowed to +2.2% to -121.4%.",
         "At 1 km, mean error ranged from +0.2% for a 1 m source to -3.7% for a 50 m source, "
         "and by 1.5 km the corresponding range had narrowed to +0.1% to -1.4%.",
         "S6.5.1 stack height 1-1.5 km")
x = R(x, "At 2 km, errors were modest for heights up to 30 m, ranging from about -3.8% (1 m) "
         "to -10.2% (30 m), though the 50 m case still produced notable underestimation "
         "(-44.9%).",
         "At 2 km, errors were negligible for heights up to 30 m, within 0.2%, and the 50 m "
         "case reached only -0.7%.",
         "S6.5.1 stack height 2 km")
x = R(x, "For example, at 3-5 km, mean errors were typically within about ±8% for heights up "
         "to 30 m, although the extreme 50 m case still yielded moderate overestimation at "
         "longer distances (+2.0% at 3 km, +8.8% at 3.5 km, +12.4% at 4 km, +14.3% at 4.5 "
         "km, and +14.6% at 5 km) (",
         "At 3-5 km, mean errors were within 0.1% for heights up to 30 m, and the extreme "
         "50 m case fell from -0.2% at 3 km to -0.1% at 5 km (",
         "S6.5.1 stack height 3-5 km")
x = R(x, "For a 10 m source, mean error ranged from +36.9% at 0.5 km to about -1.1% at 5 km, "
         "while for a 15 m source, mean error ranged from -57.1% at 0.5 km to +1.4% at 5 km.",
         "For a 10 m source, mean error ranged from +0.4% at 0.5 km to under 0.1% at 5 km; "
         "for a 15 m source, from -0.6% at 0.5 km to under 0.1% at 5 km.",
         "S6.5.1 stack height 10/15 m")
x = R(x, "Thus, the inversion performed well once the true and assumed source heights were "
         "reasonably similar and sampling occurred beyond the immediate near field (",
         "Thus the inversion performed well across the whole plausible range of release "
         "heights and at every distance sampled (",
         "S6.5.1 stack height summary")
x = R(x, "For the waste water treatment plant, assuming a release height near 12.2 m appears "
         "reasonable for plumes sampled beyond roughly 2-2.5 km, whereas estimates based on "
         "plume encounters within ~1 km are substantially more sensitive to uncertainty in "
         "effective source height (",
         "For the waste water treatment plant, assuming a release height near 12.2 m is "
         "therefore not a material source of uncertainty at any of the distances at which "
         "plumes were actually intercepted, 1.95 to 4.30 km (",
         "S6.5.1 stack height recommendation")

# ---- crosswind offsets ---------------------------------------------------
x = R(x, "At 0.5 km, mean error ranged from -2.2% for a 25 m offset to -8.3% for 50 m, "
         "-28.3% for 100 m, -70.0% for 200 m, -91.6% for 300 m, and -100.0% for 500 m.",
         "At 0.5 km, mean error ranged from -2.1% for a 25 m offset to -8.1% for 50 m, "
         "-27.7% for 100 m, -69.1% for 200 m, -91.2% for 300 m and -99.8% for 500 m.",
         "S6.5.1 crosswind 0.5 km")
x = R(x, "At 1 km, mean error ranged from -0.6% (25 m) to -2.2% (50 m), -8.2% (100 m), "
         "-31.3% (200 m), -56.0% (300 m), and -87.7% (500 m).",
         "At 1 km, mean error ranged from -0.6% (25 m) to -2.5% (50 m), -9.3% (100 m), "
         "-31.4% (200 m), -55.1% (300 m) and -86.6% (500 m).",
         "S6.5.1 crosswind 1 km")
x = R(x, "By 2 km, the corresponding errors were smaller, ranging from approximately -0.1% "
         "for a 25 m offset to -0.5% for 50 m, -1.9% for 100 m, -8.2% for 200 m, -24.7% for "
         "300 m, and -52.3% for 500 m.",
         "By 2 km, the corresponding errors were smaller, ranging from -0.2% for a 25 m "
         "offset to -0.8% for 50 m, -3.1% for 100 m, -11.8% for 200 m, -24.1% for 300 m and "
         "-51.4% for 500 m.",
         "S6.5.1 crosswind 2 km")
x = R(x, "At 5 km, mean error was -0.1% for 25 m, -0.2% for 50 m, -0.9% for 100 m, -3.4% for "
         "200 m, -7.5% for 300 m, and -19.1% for 500 m.",
         "At 5 km, mean error was -0.1% for 25 m, -0.2% for 50 m, -0.8% for 100 m, -3.3% for "
         "200 m, -7.3% for 300 m and -18.7% for 500 m.",
         "S6.5.1 crosswind 5 km")

# ---- the section's combined conclusion -----------------------------------
x = R(x, "Source-height mis-specification can produce both over- and underestimation "
         "depending on the direction of mismatch, whereas crosswind misalignment leads to "
         "systematic underestimation that becomes severe when offsets exceed ~100 m.",
         "Source-height mis-specification is a minor term throughout, at most 15% and only "
         "for an extreme 50 m release sampled at 0.5 km, whereas crosswind misalignment "
         "leads to systematic underestimation that becomes severe when offsets exceed "
         "~100 m.",
         "S6.5.1 combined conclusion")
x = R(x, "Importantly, both sources of bias are most pronounced within ~1 km of the source "
         "and diminish substantially beyond ~2-3 km.",
         "Crosswind bias is most pronounced within ~1 km of the source and diminishes "
         "substantially beyond ~2-3 km.",
         "S6.5.1 both-biases claim")
x = R(x, "At distances greater than ~3 km, emission estimates are relatively robust to "
         "plausible uncertainties in source height and modest crosswind offsets (≤50 m), "
         "though larger misalignments can still introduce moderate bias.",
         "At distances greater than ~3 km, emission estimates are robust to plausible "
         "uncertainties in source height and to modest crosswind offsets (≤50 m, under 0.5% "
         "error), though larger misalignments can still introduce moderate bias.",
         "S6.5.1 robustness claim")
x = R(x, "These findings indicate that reliable emission estimates from mobile plume "
         "sampling are most achievable when observations are obtained at intermediate "
         "distances (approximately 2-5 km), where sensitivity to geometric assumptions is "
         "minimized while plume signals remain detectable.",
         "These findings indicate that reliable emission estimates from mobile plume "
         "sampling are most achievable when observations are obtained at intermediate "
         "distances (approximately 2-5 km), where sensitivity to crosswind alignment is "
         "minimized while plume signals remain detectable. All four retained intercepts, at "
         "1.95 to 4.30 km, fall in or near that range.",
         "S6.5.1 closing recommendation")

open(P, "w", encoding="utf-8").write(x)
print("document.xml rewritten (%d bytes)" % len(x))
