"""Swap Figures 2, 3 and 4 for the versions regenerated by the 2026-08-22 run.

Figure 1 is deliberately untouched: FinalFig/Figure1_sampling_density.png still
dates from 2026-08-17 and did not change in this run.

rId -> caption adjacency was verified against the position of each caption in
document.xml, not assumed:
  rId32 blip @116239 -> "Spatial distribution of ..."      @117034  (Figure 2)
  rId33 blip @133699 -> "Weighted, smoothed source ..."    @134453  (Figure 3)
  rId35 blip @152673 -> "Persistent hotspot groups, ..."   @153468  (Figure 4)

The drawing extents already match the new aspect ratios (0.800, 0.800, 1.2727
at 6.50 in wide -> 8.125, 8.125, 5.107 in), so document.xml needs no change.
Figure 2 arrives as a PNG in a part named image4.jpg, so the part is renamed
and its relationship retargeted rather than filling a .jpg with PNG bytes.
"""
import os, re, shutil, struct, sys

U = "/mnt/user-data/uploads/Suncor/"
UN = "unpacked"

JOBS = [
    ("Figure 2", "rId32", "word/media/image4.jpg", "word/media/image4.png",
     U + "FinalFig/Figure2_sharedscale.png"),
    ("Figure 3", "rId33", "word/media/image2.png", "word/media/image2.png",
     U + "sourceprob_maps/FIG_sourceprob_6panel_p99_weighted_smoothed_TRI_KEY_CONTEXT_refuel_adjusted.png"),
    ("Figure 4", "rId35", "word/media/image1.png", "word/media/image1.png",
     U + "hotspot_source_fingerprint_outputs/FIG_Hotspot_PowerPanel_Clean.png"),
]


def png_size(p):
    b = open(p, "rb").read(33)
    assert b[:8] == b"\x89PNG\r\n\x1a\n", p + " is not a PNG"
    return struct.unpack(">II", b[16:24])


rels_path = os.path.join(UN, "word/_rels/document.xml.rels")
rels = open(rels_path, encoding="utf-8").read()
doc = open(os.path.join(UN, "word/document.xml"), encoding="utf-8").read()

for name, rid, old_part, new_part, src in JOBS:
    w, h = png_size(src)
    old_abs = os.path.join(UN, old_part)
    new_abs = os.path.join(UN, new_part)
    old_bytes = os.path.getsize(old_abs)
    if old_part != new_part:
        os.remove(old_abs)
        rels = rels.replace('Target="%s"' % old_part.replace("word/", ""),
                            'Target="%s"' % new_part.replace("word/", ""))
    shutil.copyfile(src, new_abs)
    # the extent that belongs to this rId
    m = re.search(r'<wp:extent cx="(\d+)" cy="(\d+)"/>(?:(?!<wp:extent).)*?r:embed="%s"' % rid,
                  doc, re.S)
    cx, cy = int(m.group(1)), int(m.group(2))
    want = round(cx / (w / h))
    flag = "OK" if abs(want - cy) / cy < 0.01 else "EXTENT MISMATCH"
    print("  %-9s %s  %s -> %s" % (name, rid, old_part, new_part))
    print("      %d x %d px (aspect %.4f) | %.2f x %.2f in | %s"
          % (w, h, w / h, cx / 914400, cy / 914400, flag))
    print("      %s -> %s bytes" % (f"{old_bytes:,}", f"{os.path.getsize(new_abs):,}"))
    if flag != "OK":
        sys.exit("extent %d EMU does not match aspect ratio (want %d)" % (cy, want))

open(rels_path, "w", encoding="utf-8").write(rels)
print("relationships rewritten")
