# ==============================================================
# 71  Rebuild the ROOT MASTER_hotspot_group_index.csv
# --------------------------------------------------------------
# WHY THIS EXISTS (bug found 2026-08-19):
# Two different files share the name MASTER_hotspot_group_index.csv:
#   (a) hotspot_group_reports/MASTER_hotspot_group_index.csv
#       — REGENERATED by script 31 from group_summary_persistent;
#         columns are *_in_group_summary.
#   (b) <root>/MASTER_hotspot_group_index.csv
#       — the curated index that scripts 33/34/35 (Figure 4,
#         fingerprints, directional metrics) actually READ.
# Nothing in the pipeline rewrote (b), so after a reprocessing run
# that CHANGES the group set (e.g. native-cadence averaging), (b)
# silently kept the previous run's groups and Figure 4 was built on
# stale definitions while every step reported success.
#
# This script rebuilds (b) from the current run so the two agree:
#   group_summary_persistent.csv  filtered to n_pollutants >= 3
#   + TRI columns from hotspot_group_reports/MASTER_..._with_TRI.csv
# preserving the exact column names scripts 33-35 expect.
#
# Run AFTER script 31 (groups) and 32 (TRI), BEFORE 33-35.
# ==============================================================

suppressPackageStartupMessages({ library(dplyr); library(readr) })

BASE     <- "/Users/priyanka/Downloads/Suncor"
f_groups <- file.path(BASE, "group_summary_persistent.csv")
f_tri    <- file.path(BASE, "hotspot_group_reports", "MASTER_hotspot_group_index_with_TRI.csv")
f_out    <- file.path(BASE, "MASTER_hotspot_group_index.csv")

MIN_POLLUTANTS <- 3   # manuscript definition of a multi-pollutant hotspot group

stopifnot(file.exists(f_groups), file.exists(f_tri))

grp <- readr::read_csv(f_groups, show_col_types = FALSE)
tri <- readr::read_csv(f_tri,    show_col_types = FALSE)

cat("group_summary rows:", nrow(grp), " | with_TRI rows:", nrow(tri), "\n")

sel <- grp %>% dplyr::filter(n_pollutants >= MIN_POLLUTANTS)
cat("groups with >=", MIN_POLLUTANTS, "pollutants:", nrow(sel), "\n")

tri_cols <- tri %>%
  dplyr::select(group_id, dplyr::any_of(c("tri_dist_m", "tri_dist_km", "tri_id", "tri_name")))

out <- sel %>%
  dplyr::left_join(tri_cols, by = "group_id") %>%
  dplyr::arrange(group_id)

# --- DIAGNOSTICS -------------------------------------------------
if (file.exists(f_out)) {
  prev <- readr::read_csv(f_out, show_col_types = FALSE)
  cat("\n[DIFF] previous root index:", nrow(prev), "groups; new:", nrow(out), "groups\n")
  gone  <- setdiff(prev$group_id, out$group_id)
  added <- setdiff(out$group_id, prev$group_id)
  if (length(gone))  cat("  groups DROPPED: ", paste(gone,  collapse = ", "), "\n")
  if (length(added)) cat("  groups ADDED:   ", paste(added, collapse = ", "), "\n")
  common <- intersect(prev$group_id, out$group_id)
  for (g in common) {
    a <- prev$pollutants[prev$group_id == g][1]
    b <- out$pollutants[out$group_id  == g][1]
    if (!identical(a, b)) cat(sprintf("  group %-3s composition: %s  ->  %s\n", g, a, b))
  }
  bak <- sub("\\.csv$", paste0("_backup_", format(Sys.Date(), "%Y%m%d"), ".csv"), f_out)
  file.copy(f_out, bak, overwrite = TRUE)
  cat("  [backup] ", basename(bak), "\n")
}
# BUGFIX (2026-08-20): if the column were absent, out$Longitude is NULL,
# is.na(NULL) is logical(0), and any(logical(0)) is FALSE - so the guard that
# is supposed to protect the column contract scripts 33-35 depend on passed
# silently on exactly the failure it was written for. Check presence first.
stopifnot(nrow(out) > 0,
          all(c("group_id", "Longitude", "Latitude") %in% names(out)),
          !any(is.na(out$Longitude)), !any(is.na(out$Latitude)),
          !anyDuplicated(out$group_id))

readr::write_csv(out, f_out)
cat("\n[Saved] ", f_out, " (", nrow(out), " groups)\n", sep = "")
print(as.data.frame(out[, c("group_id","n_pollutants","pollutants","total_n_days","max_n_days","tri_name")]),
      row.names = FALSE)
